services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Port local mappé sur le port exposé par le conteneur
    environment:
      - NODE_ENV=development # Définit l'environnement en mode développement
    volumes:
      - ./frontend:/app # Monte le code source local dans le conteneur
      - /app/node_modules # Empêche le conflit avec node_modules local
    command: ["npm", "run", "dev"] # Commande redéfinie pour npm run dev

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" # Backend accessible sur localhost:5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: myapp

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: