services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000" # Port local mappé sur le port exposé par le conteneur
    environment:
      - NODE_ENV=development 
    volumes:
      - ./frontend:/app 
      - /app/node_modules 
    command: ["npm", "run", "dev"] 

  backend:
    build:
      context: ./backend
    ports:
      - "6001:6001" # Backend accessible sur localhost:6001
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USERNAME}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./backend/script/initDbUser.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080" # Accessible sur localhost:8080
    depends_on:
      - db

volumes:
  postgres-data: