name: Deploy dcart app SFTP

on:
  push:
    branches: [dev]

jobs:
  ftp-deploy:
    name: Upload build via FTP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies and build frontend
      working-directory: frontend
      run: |
        npm install
        npm run build

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        port: ${{ secrets.FTP_PORT || 21 }}
        local-dir: frontend/dist
        server-dir: ${{ secrets.FTP_REMOTE_DIR }}
